#
# Default values for demo app
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
Prod:
  Replicas: 4
  ImageName: harshals/demo-go-app
  ImageTag: master.2
Canary:
  Replicas: 4
  ImageName: harshals/demo-go-app
  ImageTag: canary.2
